# Generated by Django 5.2.1 on 2025-05-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('orientador', models.CharField(max_length=100)),
                ('coorientador', models.CharField(blank=True, max_length=100)),
                ('resumo', models.TextField()),
                ('abstract', models.TextField()),
                ('palavras_chave', models.CharField(max_length=200)),
                ('data_defesa', models.DateField()),
                ('arquivo', models.FileField(upload_to='monografias/')),
            ],
        ),
    ]
